<?php

namespace panix\mod\markup\models;

use panix\engine\CMS;
use Yii;
use panix\engine\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * Class Markup
 *
 * @property integer $id
 * @property string $name
 * @property string $sum
 * @property array $categories Category ids
 * @property array $manufacturers Manufacturer ids
 * @property array $suppliers Suppliers ids
 * @package panix\mod\markup\models
 *
 */
class Markup extends ActiveRecord
{

    const MODULE_ID = 'markup';

    /**
     * @var array ids of categories to apply discount
     */
    protected $_categories;

    /**
     * @var array ids of manufacturers to apply discount
     */
     protected $_manufacturers;

    /**
     * @var array ids of manufacturers to apply discount
     */
    protected $_suppliers;

    public static $categoryTable = '{{%markup__category}}';
    public static $manufacturerTable = '{{%markup__manufacturer}}';
    public static $supplierTable = '{{%markup__supplier}}';

    //public $useRules;


    public function attributeLabels()
    {
        return \yii\helpers\ArrayHelper::merge([
            'manufacturers' => self::t('MANUFACTURERS'),
            'suppliers' => self::t('SUPPLIERS'),
            'userRoles' => self::t('USER_ROLES'),
        ], parent::attributeLabels());
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%markup}}';
    }

    public static function find()
    {
        return new MarkupQuery(get_called_class());
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'sum'], 'required'],
            ['switch', 'boolean'],
            ['name', 'string', 'max' => 255],
            ['sum', 'string', 'max' => 10],
            [['created_at', 'updated_at'], 'integer'],
            //[['discountManufacturers', 'discountCategories', 'userRoles'], 'each', 'rule' => ['integer']],
            [['manufacturers', 'categories', 'suppliers'], 'validateArray'],
            //[['manufacturers', 'categories'], 'default', 'value' => []],

            [['id', 'name', 'switch', 'sum'], 'safe'],
        ];
    }

    public function validateArray($attribute)
    {
        if (!is_array($this->{$attribute})) {
            $this->addError($attribute, 'The attribute must be array.');
        }
    }


    /**
     * @param array $data
     */
    public function setCategories($data)
    {
        $this->_categories = $data;
    }
    /**
     * @param array $data
     */
    public function setManufacturers($data)
    {
        $this->_manufacturers = $data;
    }

    /**
     * @param array $data
     */
    public function setSuppliers($data)
    {
        $this->_suppliers = $data;
    }
    /**
     * @return array
     */
    public function getCategories()
    {
        if (is_array($this->_categories))
            return $this->_categories;

        if($this->categories_data){
            $this->_categories = json_decode($this->categories_data);
        }else{
            $this->_categories = [];
        }
        return $this->_categories;
    }

    public function getManufacturers()
    {
        if (is_array($this->_manufacturers))
            return $this->_manufacturers;

        if($this->manufacturers_data){
            $this->_manufacturers = json_decode($this->manufacturers_data);
        }else{
            $this->_manufacturers = [];
        }
        return $this->_manufacturers;
    }


    public function getSuppliers()
    {
        if (is_array($this->_suppliers))
            return $this->_suppliers;

        if($this->suppliers_data){
            $this->_suppliers = json_decode($this->suppliers_data);
        }else{
            $this->_suppliers = [];
        }
        return $this->_suppliers;
    }

    public function beforeSave($insert)
    {
        //var_dump($this->categories);die;
        if ($this->categories)
            $this->categories_data = json_encode(array_unique($this->categories));
        if ($this->manufacturers)
            $this->manufacturers_data = json_encode(array_unique($this->manufacturers));
        if ($this->suppliers)
            $this->suppliers_data = json_encode(array_unique($this->suppliers));
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
